### ISSUE TITLE
mdevd paket in alpine-edge build against wrong libskarnet

### ISSUE THREAD

**Issue by BenjaminBeichler** [skarnet/mdevd#2]
I got the following error, while installing mdevd:

```
  so:libskarnet.so.2.6 (missing):
    required by:
                 mdevd-0.1.0.1-r0[so:libskarnet.so.2.6]
```
Unfortunately, the packet "skalibs" is in version 2.7, which might cause this error. Since you are also the maintainer of this packet, it should be easy to build against the new version (or build it static)

Thanks

**Comment by skarnet** [comment]
Thanks for the notice. I need to do a pass on all the Alpine packages, to update them and fix those kind of issues; unfortunately I have _very_ little free time these days. I'll try to do it next week-end.

**Comment by ghost** [comment]
up

**Comment by skarnet** [comment]
Can't do much about dynamic dependencies, it all depends on how the packages are made on the Alpine builders. I just sent a new batch of patches, including a mdevd bump; hopefully, the Edge builders will process them all at the same time and set the correct dependencies.

**Comment by ghost** [comment]
Much appreciated. I bumped because the skalibs required were still the 26.x.x ones, so I thought you forgot about this. Seems like I was wrong, thanks again.

**Comment by skarnet** [comment]
Should be long fixed. Closing this, please reopen if it's still an issue.
