### ISSUE TITLE
Rebroadcast uevents

### ISSUE THREAD

**Issue by illiliti** [skarnet/mdevd#4]
Currently, [libudev-zero](https://github.com/illiliti/libudev-zero) uses files to get uevents from device manager. I admit that this looks hacky and improper, but I can't do anything on my side.

I propose to rebroadcast uevent messages. This way, I could implement race-free file-less hotplugging for libudev-zero.

As far as I know, there are two ways how it could be done.

1. Rebroadcast uevents to named unix socket
2. Rebroadcast uevents via custom netlink group number[1]

[1]
https://man7.org/linux/man-pages/man7/netlink.7.html `nl_groups`
https://github.com/oasislinux/hotplugd/commit/6d19eb4871dddc96a80e9d92ee35d88c6889763c

**Comment by skarnet** [comment]
Isn't the `-o outputfd` option enough? Couldn't libudev-zero read the stream of events from a file descriptor? (Fields are null-terminated, and an additional null terminates the uevent.)

**Comment by illiliti** [comment]
How I'm supposed to control that option if mdevd usually started by service manager/init script? By rudely killing mdevd and restarting it with new option? No, I think this option isn't what I'm looking for. Correct me if I'm wrong.

**Comment by skarnet** [comment]
Ah, what I missed is that libudev-zero doesn't provide any daemon per se, so there needs to be a mechanism to allow _clients_ to individually subscribe to uevents.

I have no objection to adding an option to rebroadcast uevents to a netlink group, but what is the advantage of this over simply connecting to the kernel's source of uevents itself? Do you need to ensure the uevents have been processed by the device manager before notifying clients?

**Comment by illiliti** [comment]
> Do you need to ensure the uevents have been processed by the device manager before notifying clients?

Exactly. I need to ensure that there is no race condition.

**Comment by skarnet** [comment]
I will add an option to rebroadcast to netlink some time this week, but it will only be in master - the next release may not be in a while because I'm sitting on a skalibs+s6 major update, trying to cram as many incompatible changes as I need before cutting the release.

**Comment by illiliti** [comment]
Sure, take your time.

**Comment by skarnet** [comment]
master branch now supports a `-O nlgroups` option, that rebroadcasts events to the netlink groups identified by the `nlgroups` mask, with 1 ignored because it's the kernel one. Please test and tell me if it works for your purposes.

**Comment by illiliti** [comment]
Awesome. Just tested master branch by plugging/unplugging my mouse and everything works flawlessly. Thanks
