### ISSUE TITLE
kernel CONFIG_UEVENT_HELPER_PATH and mdevd

### ISSUE THREAD

**Issue by hongkongkiwi** [skarnet/mdevd#5]
By default, kernel config `CONFIG_UEVENT_HELPER_PATH` calls /bin/mdev, what should this be changed to when using mdevd?

**Comment by skarnet** [comment]
You don't need to change anything, just don't declare any helper binary in `/proc/sys/kernel/hotplug` at boot time (set it to the empty string). mdevd doesn't need a hotplug helper because it listens to uevents on the netlink.

**Comment by skarnet** [comment]
Can I close this?

**Comment by dm9pZCAq** [comment]
@hongkongkiwi this is how it's done in kiss linux
https://github.com/kisslinux/repo/blob/377d8e55db8b213507343078b5315f1aa21b265c/extra/mdevd/files/mdevd.run#L4tr

**Comment by hongkongkiwi** [comment]
Very helpful thank you.
