### ISSUE TITLE
Add support for libudev-zero

### ISSUE THREAD

**Issue by bugcrazy** [skarnet/mdevd#7]
Libudev-zero has the same license from mdevd, the code is clean and easy to maintain, libudev-zero support will increase from mdevd ability with hardware! 

https://github.com/illiliti/libudev-zero

**Comment by skarnet** [comment]
mdevd doesn't need to "add support for libudev-zero" (save a few minor changes that will be released very soon). Both projects work well together indeed, but separately; making it together is an integrator's job, and should be performed by distribution.
If @illiliti wants, we can work together to determine how we can make integration of mdevd + libudev-zero easier, at some point in the future; however, my plate is full for a couple months.

**Comment by bugcrazy** [comment]
Thanks! I'll talk to @illiliti to participate in the conversation !

**Comment by illiliti** [comment]
Further integration isn't needed. mdevd already works with libudev-zero, and vice versa.

**Comment by skarnet** [comment]
What I meant by integration was, should there be `mdev.conf` rules that would make it easier for distros to switch to a mdevd + libudev-zero model, this kind of thing.
But this can be discussed separately. I'm closing this for now, reopen if you have specific requests.
