### ISSUE TITLE
Mention `nsss` as an optional dependency

### ISSUE THREAD

**Issue by firasuke** [skarnet/mdevd#8]
The documentation on the website doesn't mention that `nsss` is an optional build-time and boot-time dependency, even though it's mentioned in the `NEWS` file that as of `0.1.0.2` support for `nsss` was added, and a `--enable-nsss` flag is listed in the configure file.

Also what kind of dependency is it? Is it only a build-time dependency, or a boot-time dependency or a run-time dependency?

**Comment by skarnet** [comment]
Good catch, will fix, thanks.

It depends on how you build nsss! In the general case it doesn't make more sense to build with nsss if you're not going to run a nsssd daemon, so it's likely a build-time _and_ run-time dependency.

**Comment by firasuke** [comment]
Ok cool, thanks for clarifying!

Leaving this open until the information on the website is updated.

**Comment by skarnet** [comment]
Done.

**Comment by firasuke** [comment]
Great work, thanks!
